-- Workshop - Configuração da Base de Dados (PostgreSQL 18)
-- Objetivo: Demonstrar o relacionamento 1-N (Proprietário -> Imóvel) com Valores Comerciais

-- Limpeza prévia para garantir a independência do script de treinamento
DROP TABLE IF EXISTS tb_imovel;
DROP TABLE IF EXISTS tb_proprietario;

-- 1. Criação da tabela PAI: Proprietario
CREATE TABLE tb_proprietario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(80) NOT NULL,
    cpf NUMERIC(11) NOT NULL,
    
    CONSTRAINT pk_proprietario PRIMARY KEY (id)
);

-- 2. Criação da tabela FILHO: imovel 
CREATE TABLE tb_imovel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(80) NOT NULL,
    valor NUMERIC(15, 2) NOT NULL,
    id_proprietario BIGINT NOT NULL,
    
    CONSTRAINT pk_imovel PRIMARY KEY (id),
    CONSTRAINT fk_imovel_proprietario FOREIGN KEY (id_proprietario) 
        REFERENCES tb_proprietario (id) ON DELETE CASCADE
);

-- 3. Carga de Dados: Proprietários
INSERT INTO tb_proprietario (nome, cpf) VALUES ('Fernando Ferreira', 34985612309);  -- ID 1
INSERT INTO tb_proprietario (nome, cpf) VALUES ('Marcio Gama', 47812390847);  		-- ID 2
INSERT INTO tb_proprietario (nome, cpf) VALUES ('Carla Dias', 23897612367);  		-- ID 3
INSERT INTO tb_proprietario (nome, cpf) VALUES ('Pedro Caxias', 45612378695);       -- ID 4
INSERT INTO tb_proprietario (nome, cpf) VALUES ('Marcelo Leopoldo', 12345697632);   -- ID 5

-- 4. Carga de Dados Refatorada: Imoveis com Preços de Mercado
-- Fernando Ferreira (id_proprietario = 1)
INSERT INTO tb_imovel (nome, valor, id_proprietario) VALUES ('Casa no lago n° 23', 1258990.00, 1);
INSERT INTO tb_imovel (nome, valor, id_proprietario) VALUES ('Apartamento Taguatinga n° 102', 775990.00, 1);
INSERT INTO tb_imovel (nome, valor, id_proprietario) VALUES ('Casa Guará n° 12', 5349990.00, 1);
INSERT INTO tb_imovel (nome, valor, id_proprietario) VALUES ('Casa Sobradinho n° 40', 7624490.00, 1);

-- Marcio Gama (id_proprietario = 2)
INSERT INTO tb_imovel (nome, valor, id_proprietario) VALUES ('Apartamento Noroeste n° 607', 2289290.00, 2);
INSERT INTO tb_imovel (nome, valor, id_proprietario) VALUES ('Apartamento Asa Norte n° 402', 1147890.00, 2);
INSERT INTO tb_imovel (nome, valor, id_proprietario) VALUES ('Apartamento Asas Norte n° 106', 760990.00, 2);
INSERT INTO tb_imovel (nome, valor, id_proprietario) VALUES ('Apartamento Cruzeiro n° 712', 815000.00, 2);

-- Carla Dias (id_proprietario = 3)
INSERT INTO tb_imovel (nome, valor, id_proprietario) VALUES ('Casa Asa Sul n° 555', 1049990.00, 3);
INSERT INTO tb_imovel (nome, valor, id_proprietario) VALUES ('Apartamento Asa Norte n° 102', 1257800.00, 3);
INSERT INTO tb_imovel (nome, valor, id_proprietario) VALUES ('Apartamento Noroeste', 5486000.00, 3);

-- Pedo Caxias (id_proprietario = 4)
INSERT INTO tb_imovel (nome, valor, id_proprietario) VALUES ('Casa São Sebastião n° 44', 849800.00, 4);
INSERT INTO tb_imovel (nome, valor, id_proprietario) VALUES ('Casa Taguatinga n° 51', 729800.00, 4);
INSERT INTO tb_imovel (nome, valor, id_proprietario) VALUES ('Casa Taguatinga n° 111', 596800.00, 4);

-- Marcelo Leopoldo (id_proprietario = 5)
INSERT INTO tb_imovel (nome, valor, id_proprietario) VALUES ('Casa Riacho Fundo n° 4', 745990.00, 5);
INSERT INTO tb_imovel (nome, valor, id_proprietario) VALUES ('Casa Sobradinho n° 56', 522490.00, 5);
INSERT INTO tb_imovel (nome, valor, id_proprietario) VALUES ('Sala SCS n° 401', 1243900.00, 5);
INSERT INTO tb_imovel (nome, valor, id_proprietario) VALUES ('Loja SQS n° 134', 212990.00, 5);


rollback;
